name: Linter

on:
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'

jobs:
  linter:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install flake8
        run: pip install flake8==4.0.1
      - name: Run linter
        run: flake8 django_shop --max-line-length=100